# Chat link Config

# This plugin will be disabled if you do not have a valid Bot Token here
# To get your bot token to go https://discord.com/Developers and create a bot there
BotToken: 1234

# This is the channel that minecraft messages will be sent to
MessagesChannel: smp-chat

# Guild/Discord Server ID (Look here if you dont know how to get that: https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)
GuildID: 0

# If verificatedRequired is set to true a player will not be able to join the server non-verified
# Default: false
VerificationRequired: false

# Verification Code Length is how long you want the verification code to be (Default: 5, Ex: QWOP5)
# Unverification Code Length is how long you want the Unverification code to be (Default: 8, Ex: EDOPA7H1)
# Verification Code is the first time login code that a player must enter to join the server
# Unverification Code is the code a user must input after they have been unverified
VerificationCodeLength: 5
UnverificationCodeLength: 8

# This is the role that will be checked for sendmessages permission in channels
# EITHER PUT THE ID OR THE ROLE NAME IF THE BOT FINDS TWO OR MORE ROLES WITH THIS NAME IT WILL AUTOMATICALLY DEFAULT TO @EVERYONE
# Default: Everyone
RoleChecked: everyone

# Save the last used channel a player sent a message to
# Default: false
SaveLastUsedChannel: false